# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visulisation.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1227, 708)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color: rgb(214, 214, 214);\n"
"}\n"
"QMenuBar{\n"
"background-color: rgb(236, 236, 236);\n"
"}")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sa_demo = QtWidgets.QGraphicsView(self.centralwidget)
        self.sa_demo.setGeometry(QtCore.QRect(17, 26, 451, 381))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sa_demo.sizePolicy().hasHeightForWidth())
        self.sa_demo.setSizePolicy(sizePolicy)
        self.sa_demo.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.sa_demo.setMouseTracking(False)
        self.sa_demo.setStyleSheet("QGraphicsView{\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 245, 245)\n"
"}")
        self.sa_demo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.sa_demo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.sa_demo.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.sa_demo.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.sa_demo.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.sa_demo.setResizeAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.sa_demo.setViewportUpdateMode(QtWidgets.QGraphicsView.FullViewportUpdate)
        self.sa_demo.setObjectName("sa_demo")
        self.phenology_information_view = QtWidgets.QGraphicsView(self.centralwidget)
        self.phenology_information_view.setGeometry(QtCore.QRect(477, 26, 741, 631))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phenology_information_view.sizePolicy().hasHeightForWidth())
        self.phenology_information_view.setSizePolicy(sizePolicy)
        self.phenology_information_view.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.phenology_information_view.setStyleSheet("QGraphicsView{\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 245, 245)\n"
"}")
        self.phenology_information_view.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.phenology_information_view.setObjectName("phenology_information_view")
        self.label_sa_demo = QtWidgets.QLabel(self.centralwidget)
        self.label_sa_demo.setGeometry(QtCore.QRect(17, -4, 451, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sa_demo.sizePolicy().hasHeightForWidth())
        self.label_sa_demo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_sa_demo.setFont(font)
        self.label_sa_demo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_sa_demo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sa_demo.setObjectName("label_sa_demo")
        self.Initialization_box = QtWidgets.QGroupBox(self.centralwidget)
        self.Initialization_box.setEnabled(True)
        self.Initialization_box.setGeometry(QtCore.QRect(17, 416, 310, 85))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Initialization_box.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Initialization_box.setFont(font)
        self.Initialization_box.setAutoFillBackground(False)
        self.Initialization_box.setStyleSheet("QGroupBox{\n"
"\n"
"}")
        self.Initialization_box.setFlat(False)
        self.Initialization_box.setCheckable(False)
        self.Initialization_box.setObjectName("Initialization_box")
        self.label_4 = QtWidgets.QLabel(self.Initialization_box)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 55, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.manual_input_date_Edit = QtWidgets.QLineEdit(self.Initialization_box)
        self.manual_input_date_Edit.setGeometry(QtCore.QRect(70, 20, 71, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_input_date_Edit.sizePolicy().hasHeightForWidth())
        self.manual_input_date_Edit.setSizePolicy(sizePolicy)
        self.manual_input_date_Edit.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.manual_input_date_Edit.setFont(font)
        self.manual_input_date_Edit.setStyleSheet("")
        self.manual_input_date_Edit.setAlignment(QtCore.Qt.AlignCenter)
        self.manual_input_date_Edit.setObjectName("manual_input_date_Edit")
        self.try_Button = QtWidgets.QPushButton(self.Initialization_box)
        self.try_Button.setGeometry(QtCore.QRect(150, 20, 51, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.try_Button.sizePolicy().hasHeightForWidth())
        self.try_Button.setSizePolicy(sizePolicy)
        self.try_Button.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.try_Button.setFont(font)
        self.try_Button.setObjectName("try_Button")
        self.random_input_Button = QtWidgets.QPushButton(self.Initialization_box)
        self.random_input_Button.setGeometry(QtCore.QRect(210, 20, 91, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.random_input_Button.sizePolicy().hasHeightForWidth())
        self.random_input_Button.setSizePolicy(sizePolicy)
        self.random_input_Button.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.random_input_Button.setFont(font)
        self.random_input_Button.setStyleSheet("")
        self.random_input_Button.setObjectName("random_input_Button")
        self.label_3 = QtWidgets.QLabel(self.Initialization_box)
        self.label_3.setGeometry(QtCore.QRect(2, 55, 71, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.sa_combobox = QtWidgets.QComboBox(self.Initialization_box)
        self.sa_combobox.setGeometry(QtCore.QRect(70, 55, 71, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sa_combobox.sizePolicy().hasHeightForWidth())
        self.sa_combobox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.sa_combobox.setFont(font)
        self.sa_combobox.setObjectName("sa_combobox")
        self.gamma_correction_button = QtWidgets.QPushButton(self.Initialization_box)
        self.gamma_correction_button.setEnabled(False)
        self.gamma_correction_button.setGeometry(QtCore.QRect(150, 54, 71, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gamma_correction_button.sizePolicy().hasHeightForWidth())
        self.gamma_correction_button.setSizePolicy(sizePolicy)
        self.gamma_correction_button.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.gamma_correction_button.setFont(font)
        self.gamma_correction_button.setObjectName("gamma_correction_button")
        self.gamma_para_spinbox = QtWidgets.QDoubleSpinBox(self.Initialization_box)
        self.gamma_para_spinbox.setEnabled(False)
        self.gamma_para_spinbox.setGeometry(QtCore.QRect(230, 54, 71, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gamma_para_spinbox.sizePolicy().hasHeightForWidth())
        self.gamma_para_spinbox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.gamma_para_spinbox.setFont(font)
        self.gamma_para_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.gamma_para_spinbox.setSingleStep(0.01)
        self.gamma_para_spinbox.setProperty("value", 1.52)
        self.gamma_para_spinbox.setObjectName("gamma_para_spinbox")
        self.VI_para_box = QtWidgets.QGroupBox(self.centralwidget)
        self.VI_para_box.setEnabled(False)
        self.VI_para_box.setGeometry(QtCore.QRect(17, 513, 310, 87))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.VI_para_box.setFont(font)
        self.VI_para_box.setObjectName("VI_para_box")
        self.inundated_combobox = QtWidgets.QComboBox(self.VI_para_box)
        self.inundated_combobox.setGeometry(QtCore.QRect(105, 54, 75, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inundated_combobox.sizePolicy().hasHeightForWidth())
        self.inundated_combobox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.inundated_combobox.setFont(font)
        self.inundated_combobox.setObjectName("inundated_combobox")
        self.inundated_combobox.addItem("")
        self.label_5 = QtWidgets.QLabel(self.VI_para_box)
        self.label_5.setGeometry(QtCore.QRect(5, 55, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.VI_para_box)
        self.label_2.setGeometry(QtCore.QRect(7, 23, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.vi_combobox = QtWidgets.QComboBox(self.VI_para_box)
        self.vi_combobox.setGeometry(QtCore.QRect(105, 22, 75, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vi_combobox.sizePolicy().hasHeightForWidth())
        self.vi_combobox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.vi_combobox.setFont(font)
        self.vi_combobox.setObjectName("vi_combobox")
        self.vi_combobox.addItem("")
        self.label_6 = QtWidgets.QLabel(self.VI_para_box)
        self.label_6.setGeometry(QtCore.QRect(141, 23, 126, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(126, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.display_button = QtWidgets.QPushButton(self.VI_para_box)
        self.display_button.setGeometry(QtCore.QRect(184, 52, 55, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display_button.sizePolicy().hasHeightForWidth())
        self.display_button.setSizePolicy(sizePolicy)
        self.display_button.setMinimumSize(QtCore.QSize(0, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.display_button.setFont(font)
        self.display_button.setObjectName("display_button")
        self.rescale_button = QtWidgets.QPushButton(self.VI_para_box)
        self.rescale_button.setGeometry(QtCore.QRect(244, 52, 55, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rescale_button.sizePolicy().hasHeightForWidth())
        self.rescale_button.setSizePolicy(sizePolicy)
        self.rescale_button.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.rescale_button.setFont(font)
        self.rescale_button.setObjectName("rescale_button")
        self.doy_line_box = QtWidgets.QLineEdit(self.VI_para_box)
        self.doy_line_box.setGeometry(QtCore.QRect(228, 22, 71, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doy_line_box.sizePolicy().hasHeightForWidth())
        self.doy_line_box.setSizePolicy(sizePolicy)
        self.doy_line_box.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.doy_line_box.setFont(font)
        self.doy_line_box.setAlignment(QtCore.Qt.AlignCenter)
        self.doy_line_box.setObjectName("doy_line_box")
        self.label_6.raise_()
        self.inundated_combobox.raise_()
        self.label_5.raise_()
        self.label_2.raise_()
        self.vi_combobox.raise_()
        self.display_button.raise_()
        self.rescale_button.raise_()
        self.doy_line_box.raise_()
        self.label_sa_demo_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_sa_demo_2.setGeometry(QtCore.QRect(477, -4, 741, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sa_demo_2.sizePolicy().hasHeightForWidth())
        self.label_sa_demo_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_sa_demo_2.setFont(font)
        self.label_sa_demo_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_sa_demo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sa_demo_2.setObjectName("label_sa_demo_2")
        self.phenology_factor_box = QtWidgets.QGroupBox(self.centralwidget)
        self.phenology_factor_box.setEnabled(False)
        self.phenology_factor_box.setGeometry(QtCore.QRect(17, 610, 451, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.phenology_factor_box.setFont(font)
        self.phenology_factor_box.setObjectName("phenology_factor_box")
        self.phenology_view_box = QtWidgets.QComboBox(self.phenology_factor_box)
        self.phenology_view_box.setEnabled(False)
        self.phenology_view_box.setGeometry(QtCore.QRect(98, 20, 91, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.phenology_view_box.setFont(font)
        self.phenology_view_box.setObjectName("phenology_view_box")
        self.phenology_view_box.addItem("")
        self.phenology_view_box.addItem("")
        self.time_span_begin = QtWidgets.QComboBox(self.phenology_factor_box)
        self.time_span_begin.setEnabled(False)
        self.time_span_begin.setGeometry(QtCore.QRect(71, 49, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.time_span_begin.setFont(font)
        self.time_span_begin.setObjectName("time_span_begin")
        self.time_span_begin.addItem("")
        self.time_span_end = QtWidgets.QComboBox(self.phenology_factor_box)
        self.time_span_end.setEnabled(False)
        self.time_span_end.setGeometry(QtCore.QRect(137, 49, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.time_span_end.setFont(font)
        self.time_span_end.setObjectName("time_span_end")
        self.time_span_end.addItem("")
        self.label_7 = QtWidgets.QLabel(self.phenology_factor_box)
        self.label_7.setGeometry(QtCore.QRect(7, 50, 61, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.phenology_factor_box)
        self.label_8.setGeometry(QtCore.QRect(120, 48, 16, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.phenology_factor_box)
        self.label_9.setGeometry(QtCore.QRect(10, 22, 81, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label = QtWidgets.QLabel(self.phenology_factor_box)
        self.label.setGeometry(QtCore.QRect(189, 21, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.ra_domain_box = QtWidgets.QComboBox(self.phenology_factor_box)
        self.ra_domain_box.setEnabled(False)
        self.ra_domain_box.setGeometry(QtCore.QRect(290, 20, 71, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.ra_domain_box.setFont(font)
        self.ra_domain_box.setObjectName("ra_domain_box")
        self.ra_domain_box.addItem("")
        self.ra_domain_box.addItem("")
        self.label_10 = QtWidgets.QLabel(self.phenology_factor_box)
        self.label_10.setGeometry(QtCore.QRect(190, 50, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.regression_box = QtWidgets.QComboBox(self.phenology_factor_box)
        self.regression_box.setEnabled(False)
        self.regression_box.setGeometry(QtCore.QRect(290, 50, 71, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regression_box.sizePolicy().hasHeightForWidth())
        self.regression_box.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.regression_box.setFont(font)
        self.regression_box.setObjectName("regression_box")
        self.regression_box.addItem("")
        self.regression_box.addItem("")
        self.regression_box.addItem("")
        self.generate_button = QtWidgets.QPushButton(self.phenology_factor_box)
        self.generate_button.setEnabled(False)
        self.generate_button.setGeometry(QtCore.QRect(370, 20, 71, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generate_button.sizePolicy().hasHeightForWidth())
        self.generate_button.setSizePolicy(sizePolicy)
        self.generate_button.setMinimumSize(QtCore.QSize(0, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.generate_button.setFont(font)
        self.generate_button.setObjectName("generate_button")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setEnabled(False)
        self.groupBox_4.setGeometry(QtCore.QRect(337, 415, 131, 181))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.display_button_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.display_button_2.setGeometry(QtCore.QRect(15, 22, 100, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display_button_2.sizePolicy().hasHeightForWidth())
        self.display_button_2.setSizePolicy(sizePolicy)
        self.display_button_2.setMinimumSize(QtCore.QSize(0, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.display_button_2.setFont(font)
        self.display_button_2.setObjectName("display_button_2")
        self.display_button_3 = QtWidgets.QPushButton(self.groupBox_4)
        self.display_button_3.setGeometry(QtCore.QRect(15, 57, 100, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display_button_3.sizePolicy().hasHeightForWidth())
        self.display_button_3.setSizePolicy(sizePolicy)
        self.display_button_3.setMinimumSize(QtCore.QSize(0, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.display_button_3.setFont(font)
        self.display_button_3.setObjectName("display_button_3")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(474, 665, 461, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(940, 667, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_sa_demo.raise_()
        self.label_sa_demo_2.raise_()
        self.VI_para_box.raise_()
        self.Initialization_box.raise_()
        self.sa_demo.raise_()
        self.phenology_information_view.raise_()
        self.phenology_factor_box.raise_()
        self.groupBox_4.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1227, 18))
        self.menubar.setStyleSheet("background-color: #c1cbd7")
        self.menubar.setObjectName("menubar")
        self.menuFiles = QtWidgets.QMenu(self.menubar)
        self.menuFiles.setAutoFillBackground(False)
        self.menuFiles.setStyleSheet("")
        self.menuFiles.setObjectName("menuFiles")
        self.menuPara = QtWidgets.QMenu(self.menubar)
        self.menuPara.setObjectName("menuPara")
        self.menuOuput = QtWidgets.QMenu(self.menubar)
        self.menuOuput.setObjectName("menuOuput")
        MainWindow.setMenuBar(self.menubar)
        self.actionclose = QtWidgets.QAction(MainWindow)
        self.actionclose.setObjectName("actionclose")
        self.actionKey_dictionary_path = QtWidgets.QAction(MainWindow)
        self.actionKey_dictionary_path.setObjectName("actionKey_dictionary_path")
        self.actionUpdate_the_root_path = QtWidgets.QAction(MainWindow)
        self.actionUpdate_the_root_path.setObjectName("actionUpdate_the_root_path")
        self.actionUpdate_Key_dictionary_path = QtWidgets.QAction(MainWindow)
        self.actionUpdate_Key_dictionary_path.setObjectName("actionUpdate_Key_dictionary_path")
        self.actionUpdate_fundamental_dic = QtWidgets.QAction(MainWindow)
        self.actionUpdate_fundamental_dic.setObjectName("actionUpdate_fundamental_dic")
        self.actionUpdate_Original_file_path = QtWidgets.QAction(MainWindow)
        self.actionUpdate_Original_file_path.setObjectName("actionUpdate_Original_file_path")
        self.actionUpdate_shpfile_path = QtWidgets.QAction(MainWindow)
        self.actionUpdate_shpfile_path.setObjectName("actionUpdate_shpfile_path")
        self.actionRegression_parameters = QtWidgets.QAction(MainWindow)
        self.actionRegression_parameters.setObjectName("actionRegression_parameters")
        self.actionOuput_folder = QtWidgets.QAction(MainWindow)
        self.actionOuput_folder.setObjectName("actionOuput_folder")
        self.actionOuput_Figure = QtWidgets.QAction(MainWindow)
        self.actionOuput_Figure.setObjectName("actionOuput_Figure")
        self.actionOutput_Data = QtWidgets.QAction(MainWindow)
        self.actionOutput_Data.setObjectName("actionOutput_Data")
        self.menuFiles.addAction(self.actionclose)
        self.menuFiles.addSeparator()
        self.menuFiles.addAction(self.actionUpdate_the_root_path)
        self.menuFiles.addAction(self.actionUpdate_Original_file_path)
        self.menuFiles.addAction(self.actionUpdate_Key_dictionary_path)
        self.menuFiles.addSeparator()
        self.menuFiles.addAction(self.actionUpdate_fundamental_dic)
        self.menuFiles.addAction(self.actionUpdate_shpfile_path)
        self.menuPara.addAction(self.actionRegression_parameters)
        self.menuOuput.addAction(self.actionOuput_folder)
        self.menuOuput.addSeparator()
        self.menuOuput.addAction(self.actionOuput_Figure)
        self.menuOuput.addAction(self.actionOutput_Data)
        self.menubar.addAction(self.menuFiles.menuAction())
        self.menubar.addAction(self.menuPara.menuAction())
        self.menubar.addAction(self.menuOuput.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Phe Inform Visulisation v0.01.1"))
        self.label_sa_demo.setText(_translate("MainWindow", "Demo of the study area"))
        self.Initialization_box.setTitle(_translate("MainWindow", "Initialization"))
        self.label_4.setText(_translate("MainWindow", "Demo Date"))
        self.manual_input_date_Edit.setText(_translate("MainWindow", "20000000"))
        self.try_Button.setText(_translate("MainWindow", "Try"))
        self.random_input_Button.setText(_translate("MainWindow", "Random Demo"))
        self.label_3.setText(_translate("MainWindow", "Study Area"))
        self.gamma_correction_button.setText(_translate("MainWindow", "γ correction"))
        self.VI_para_box.setTitle(_translate("MainWindow", "VI Display"))
        self.inundated_combobox.setItemText(0, _translate("MainWindow", "None"))
        self.label_5.setText(_translate("MainWindow", "Inundation Con"))
        self.label_2.setText(_translate("MainWindow", "Vegetation Index"))
        self.vi_combobox.setItemText(0, _translate("MainWindow", "None"))
        self.label_6.setText(_translate("MainWindow", "DOY"))
        self.display_button.setText(_translate("MainWindow", "Display"))
        self.rescale_button.setText(_translate("MainWindow", "Rescale"))
        self.doy_line_box.setText(_translate("MainWindow", "2000000"))
        self.label_sa_demo_2.setText(_translate("MainWindow", "Phenology information of the study area"))
        self.phenology_factor_box.setTitle(_translate("MainWindow", "Phenology factor"))
        self.phenology_view_box.setItemText(0, _translate("MainWindow", "Annual"))
        self.phenology_view_box.setItemText(1, _translate("MainWindow", "Overview"))
        self.time_span_begin.setItemText(0, _translate("MainWindow", "0000"))
        self.time_span_end.setItemText(0, _translate("MainWindow", "0000"))
        self.label_7.setText(_translate("MainWindow", "Time Span"))
        self.label_8.setText(_translate("MainWindow", "-"))
        self.label_9.setText(_translate("MainWindow", "Phenology view"))
        self.label.setText(_translate("MainWindow", "Research Domain"))
        self.ra_domain_box.setItemText(0, _translate("MainWindow", "Entire SA"))
        self.ra_domain_box.setItemText(1, _translate("MainWindow", "Pixel"))
        self.label_10.setText(_translate("MainWindow", "Regression type"))
        self.regression_box.setItemText(0, _translate("MainWindow", "None"))
        self.regression_box.setItemText(1, _translate("MainWindow", "SPLF"))
        self.regression_box.setItemText(2, _translate("MainWindow", "TTF"))
        self.generate_button.setText(_translate("MainWindow", "Generate"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Output"))
        self.display_button_2.setText(_translate("MainWindow", "Output Figure"))
        self.display_button_3.setText(_translate("MainWindow", "Output Data"))
        self.label_13.setText(_translate("MainWindow", "Fuction"))
        self.label_14.setText(_translate("MainWindow", "R^2"))
        self.menuFiles.setTitle(_translate("MainWindow", "Files"))
        self.menuPara.setTitle(_translate("MainWindow", "Parameters"))
        self.menuOuput.setTitle(_translate("MainWindow", "Ouput"))
        self.actionclose.setText(_translate("MainWindow", "Close"))
        self.actionKey_dictionary_path.setText(_translate("MainWindow", "Key dictionary path"))
        self.actionUpdate_the_root_path.setText(_translate("MainWindow", "Update the root path"))
        self.actionUpdate_Key_dictionary_path.setText(_translate("MainWindow", "Update Key dictionary path"))
        self.actionUpdate_fundamental_dic.setText(_translate("MainWindow", "Update fundamental dictionary"))
        self.actionUpdate_Original_file_path.setText(_translate("MainWindow", "Update Original file path"))
        self.actionUpdate_shpfile_path.setText(_translate("MainWindow", "Update shpfile "))
        self.actionRegression_parameters.setText(_translate("MainWindow", "Regression parameters"))
        self.actionOuput_folder.setText(_translate("MainWindow", "Change output Destination"))
        self.actionOuput_Figure.setText(_translate("MainWindow", "Ouput Figure"))
        self.actionOutput_Data.setText(_translate("MainWindow", "Output Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

